#!/bin/bash

if [[ "$(id -u)" -ne 0 ]]; then
    echo "sudo privilege is required to run this script!"
    exit 1
fi

# It will install packages.
#   - neovim
#   - nginx
#   - ufw
#   - tree
if pacman -Syu --noconfirm > /dev/null &&
    pacman -S --noconfirm neovim > /dev/null &&
    pacman -S --noconfirm nginx > /dev/null &&
    pacman -S --noconfirm ufw > /dev/null &&
    pacman -S --noconfirm tree > /dev/null &&
    pacman -Syu --noconfirm > /dev/null; then
    echo "packages instalation success!"
else
    echo "packages instalation failed!"
    exit 1
fi

# change time zone
timedatectl set-timezone America/Vancouver
echo "timezone has changed!"

# create system user webgen with a home directory at `/var/lib/webgen` and as a non-login user.
if useradd -r -m -d /var/lib/webgen -s /usr/sbin/nologin webgen &&
    mkdir /var/lib/webgen/bin /var/lib/webgen/HTML /var/lib/webgen/documents; then
        echo "system user 'webgen' has been created!"
else
    echo "creating system user 'webgen' has failed!"
    exit 1
fi

# create files
if echo "hello this is file one" > /var/lib/webgen/documents/file-one &&
    echo "hello this is file two" > /var/lib/webgen/documents/file-two; then
        echo "test files created!"
else
    echo "creating test files has failed!"
    exit 1
fi

# move `generate_index` to the `/var/lib/webgen/bin`
if mv ./linux-assignment3-part2/packages/generate_index /var/lib/webgen/bin &&
# change the permission of generate_index
    chmod +x /var/lib/webgen/bin/generate_index &&
# change ownership to user webgen
    chown -R webgen:webgen /var/lib/webgen/ &&
# Move a service file service and timer and nginx.conf
    mv ./linux-assignment3-part2/packages/generate_index.service /etc/systemd/system/generate_index.service &&
    mv ./linux-assignment3-part2/packages/generate_index.timer /etc/systemd/system/generate_index.timer &&
    mv ./linux-assignment3-part2/packages/nginx.conf /etc/nginx/nginx.conf &&
# create directories for management
    mkdir /etc/nginx/sites-available /etc/nginx/sites-enabled &&
# move server block file
    mv ./linux-assignment3-part2/packages/webgen.conf /etc/nginx/sites-available/webgen.conf; then
        echo "configuration files moved!"
else
    echo "moving config files failed!"
    exit 1
fi
# enabling config files
if ln -s /etc/nginx/sites-available/webgen.conf /etc/nginx/sites-enabled/webgen.conf >/dev/null &&
systemctl daemon-reload &&
systemctl enable --now generate_index.service &&
systemctl enable --now generate_index.timer &&
systemctl start nginx.service; then
    echo "configuration flies enabled!"
else
    echo "failed to enable configuration flies!"
    exit 1
fi

# ufw setting
if ufw allow ssh &&
ufw allow http &&
ufw limit ssh &&
systemctl enable --now ufw.service; then
echo "ufw setting success!"
else
    echo "failed to setting ufw!"
    exit 1
fi
echo
echo "script finished!"
echo