#!/bin/bash

# 'firstFirst' script does:
#   - download necessary packages
#   - change permission
#   - etc.

if [[ "$(id -u)" -ne 0 ]]; then
    echo "sudo privilege is required to run this script!"
    exit 1
fi

# 'installPackage' part does:
#   - It will provide and run a funtion to install packages.
#   - neovim
#   - nginx
#   - tree
pacman -Syu --noconfirm > /dev/null
pacman -S --noconfirm neovim > /dev/null || { echo "neovim install failed!"; exit 1; }
pacman -S --noconfirm nginx > /dev/null || { echo "nginx install failed!"; exit 1; }
pacman -S --noconfirm tree > /dev/null || { echo "tree install failed!"; exit 1; }
pacman -Syu --noconfirm > /dev/null
echo "packages installed!"

# change to unix
dos2unix ./packages/generate_index || { echo "changing permission of generate_index failed!"; exit 1; }
dos2unix ./checkCheck || { echo "changing permission of checkCheck failed!"; exit 1; }
dos2unix ./configScript || { echo "changing permission of configScript failed!"; exit 1; }

# change execution permission
chmod u+x checkCheck configScript || { echo "chmoding failed!"; exit 1; }

# change time zone
timedatectl set-timezone America/Vancouver
echo "script finished!"